config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'members'

  resources :users, shallow: true do
    resources :profile, :photos do
      resource :likes, :followers, :comments
    end
  end
   root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :profile
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  has_many :comments

   has_attached_file :image, :styles => { :large => "1000x1000>", :medium => "500x500>", :thumb => "200x200>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :followers

   has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    @comment.photo_id = params[:photo_id]
    @comment.save
    redirect_to photo_path(params[:photo_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def create
     @profile = Profile.find(params[:profile_id])
     @profile.followers.create     
     render json: {new_followers_count: @profile.followers.count}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
  @photos = Photo.all
  @profiles = Profile.all
end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @photo = Photo.find(params[:photo_id])
    @photo.likes.create
    render json: {new_likes_count: @photo.likes.count}
  end
  
  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
  end
  
  def create
    @photo = Photo.create(photo_params)
    @photo.user_id = current_user.id
    @photo.save
    if @photo.save
      redirect_to user_profile_index_path(current_user)
    else 
      flash[:notice] = 'please upload a photo'
      redirect_to new_user_photo_path(current_user)
    end
  end

  def show
    @photo = Photo.find_by(id: params[:id])
    @comments = Comment.where(photo_id: @photo.id)
    @profile = Profile.find_by(id: @photo.user_id)
  end

  def photo_params
    params.require(:photo).permit(:title, :location, :image)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
 def new
 end

 def create
   @profile = Profile.create(profile_params)
   @profile.user_id = current_user.id
   @profile.save
   redirect_to user_profile_index_path(current_user) 
 end

 def profile_params
   params.require(:profile).permit(:username, :name, :location, :bio, :image)
 end

 def index
   @profile = Profile.find_by(user_id: params[:user_id])
   @photos = Photo.where(user_id: @profile.user_id)
 end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 def new
 end

 def create
   @profile = Profile.create(profile_params)
   @profile.user_id = current_user.id
   @profile.save
   redirect_to user_profile_path(current_user) 
 end

 def profile_params
   params.require(:profile).permit(:username, :name, :location, :bio, :image)
 end

 def show
   @profile = Profile.find_by(user_id: current_user.id)
   @photos = Photo.where(user_id: current_user.id).all
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<h1 class='title'>insta</h1>
<h3 id="subheader">a platform for sharing photos</h3>
<h4>popular photos</h4>
<div id="popular-photos">
  <% if @photos %>
    <% @photos.each do |photo| %>
      <div id='photos'>
      <h5><%= photo.title %></h5>
      <%= link_to image_tag(photo.image.url(:medium), id: 'recent-photo') ,photo_path(photo.id), id: photo.title %>
      <p><span class="likes_count"> <%= photo.likes.count %> </span> <%= 'like'.pluralize(photo.likes.count) %><br>
      <%= link_to 'like', photo_likes_path(photo.id), class: 'likes-link' %></p>
    </div>
    <% end %>
    <% else %>
      <p>no users yet</p>
  <% end %>
</div>
<h4>popular users</h4>
<div id='popular_users'>
  <% if @profiles %>
    <% @profiles.each do |profile| %>
      <div id='profiles'>
        <h5> <%= link_to profile.username,  user_profile_index_path(profile.user_id) %> </h5>
        <div><%= image_tag profile.image.url(:thumb), class: "profile-image" %></div>
        <p> <span class='follow_count'> <%= profile.followers.count %> </span> <%= 'follower'.pluralize(profile.followers.count) %><br>
        <%= link_to 'follow', profile_followers_path(profile.id), class: 'follow-link' %></p>
    </div>
    <% end %>
    <% else %>
      <p>no users yet</p>
    <% end %>
</div>
<h4>photos for you</h4>
<div id='users_photos'></div>

app/views/photos/new.html.erb
<%= form_for Photo.new, url: user_photos_path, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/photos/show.html.erb
<h1><%=  @photo.title %> </h1>
<h3 id="subheader"><%= "by: #{@profile.username}" %>
<div id='solo-image'>
  <%= image_tag @photo.image.url(:large), class: 'solo-image' %>
</div>
<% @comments.each do |comment| %>
  <p class="comment">
  <%= comment.text %>
  </p>
  <% @profile = Profile.find_by(user_id: comment.user_id) %>
  <p class="author"><%="  written by: #{ @profile.username}" %>
  </p>
<% end %>
<%= form_for Comment.new, url: photo_comments_path(@photo.id) do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

app/views/profiles/new.html.erb
<%= form_for Profile.new, url: user_profile_path, html: { multipart: true } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :bio %>
  <%= f.text_field :bio %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/profiles/show.html.erb
<h1>your profile</h1>
<%="name: #{ @profile.name }" %>
<%="username: #{ @profile.username }" %>
<%="location: #{ @profile.location }" %>
<%="bio: #{ @profile.bio }" %>
<%= image_tag @profile.image.url(:thumb) %>
<h3>your photos</h3>
<% if @photos.empty? %>
  no photos yet
<% else %>
  <% @photos.each do |photo| %>
    <%= photo.title %>
    <%= photo.location %>
    <%= image_tag photo.image.url(:thumb) %>
  <% end %>
<% end %>
<%= link_to "add a photo", new_user_photos_path %>